import time
import math
time.sleep(1)
print("PYTHON DIVIDER"
time.sleep(2)
a = input('Please input the first numerator:     ')
b = input('Please input your first denominator:  ')
c = input('Please input your second numerator:   ')
d = input('Please input your second denominator: ')
e = input('Please input your third numerator:    ')
f = input('Please input your third denominator:  ')
a1 = (int(a)*int(d))
c1 = (int(c)*int(b))
d1 = (int(d)*int(b))
e1 = (int(e)*int(d1))
f1 = (int(f)*int(d1))
a2 = (int(a1)*int(f))
c2 = (int(c1)*int(f))
ans = (int(a2)+int(c2)+int(e1))
ans2 = math.gcd(ans , f1)
ans3 = (int(ans)/int(ans2))
ans4 = (int(f1)/int(ans2))
"""filler"""
print("")
print("PLEASE WAIT, COMPUTING...")
time.sleep(1)
print("")
print(("Answer in fractions:"),int(ans3),"/",int(ans4))
time.sleep(0.1)
print("Divided:",(ans/f1))